name: Add Secrets to GitHub Repo



on:
  push:
    branches:
      - main


jobs:
  multi-environment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, test, int]

    steps:
      - name: Setup Environment 1
        run: |
          if [ ${{ matrix.environment }} == "dev" ]; then
            # Add commands to set up environment 1 here
            echo "Setting up Environment 1"
          fi

      - name: Setup Environment 2
        run: |
          if [ ${{ matrix.environment }} in "dev1" ]; then
            # Add commands to set up environment 2 here
            echo "Setting up Environment 2"
          fi

      - name: Setup Environment 3
        run: |
          if [ ${{ matrix.environment }} == "int" ]; then
            # Add commands to set up environment 3 here
            echo "Setting up Environment 3"
          fi
