name: Add Secrets to GitHub Repo



on:
  push:
    branches:
      - main



jobs:
  add-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Secrets
      env:
        SECRET_NAME: "your_secret_name"
        SECRET_VALUE: "your_secret_value"
        GITHUB_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}
      run: |
        gh api -H "Accept: application/vnd.github+json" repos/n509249/Demo_project | jq .id  