name: Build and Test for Repository 2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    call-workflow:
      uses: Demo_project/.github/workflows/blank.yml@main