name: Add Secrets to GitHub Repo



on:
  push:
    branches:
      - main



jobs:
  add-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Secrets
      env:
        SECRET_NAME: "your_secret_name"
        SECRET_VALUE: "your_secret_value"
        GITHUB_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        Secrte_value=$(curl --globoff --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/32754322/variables/TF_CLI_ARGS_init?filter[environment_scope]=dev" | jq --raw-output '.value')
        echo $Secrte_value
        Repo_id=$(gh api -H "Accept: application/vnd.github+json" repos/n509249/Demo_project | jq .id)
        Public_key=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repositories/$Repo_id/environments/dev/secrets/public-key | jq --raw-output '.key_id')
        Base64_encoded_value=$(echo -n "$Secret_value" | base64)
        #curl -L -X PUT   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer $GITHUB_TOKEN"   -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repositories/$Repo_id/environments/dev/secrets/TF_CLI_ARGS_init  -d '{\"encrypted_value\":\"$(echo -n $SECRET_VALUE | base64 --wrap=0)\","key_id":"'"$Public_key"'"}'
        curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repositories/$Repo_id/environments/dev/secrets/TF_CLI_ARGS_init" -d "{\"encrypted_value\":\"$Base64_encoded_value\",\"key_id\":\"$Public_key\"}"
        echo $Repo_id